# Generated by Django 2.1.4 on 2019-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/profiles/no-profile.png', upload_to='media/profiles'),
        ),
    ]
