# Generated by Django 2.1.4 on 2019-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profiles/profile_standart.png', upload_to='profiles/'),
        ),
    ]
