# Generated by Django 2.1.4 on 2019-01-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190103_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='profiles/profile_standart.png', upload_to='profiles/'),
        ),
    ]
