# Generated by Django 2.1.4 on 2018-12-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_first',
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
