# Generated by Django 2.1.4 on 2018-12-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20181224_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
