# Generated by Django 2.1.4 on 2018-12-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20181227_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subforum',
        ),
    ]
