# Generated by Django 2.1.4 on 2018-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_remove_message_subforum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(default='', to='sections.Tag'),
        ),
    ]
