# Generated by Django 2.1.4 on 2019-01-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_auto_20181231_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='theme',
            field=models.CharField(max_length=200),
        ),
    ]
