# Generated by Django 2.1.4 on 2019-01-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20190101_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(to='sections.Tag'),
        ),
    ]
